version: "3"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  grafana:
    image: grafana/grafana:7.3.1
    ports:
      - 3000:3000
    networks:
      - grafana

  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - grafana
    env_file:
      - .env

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana
