{
 "title": "Twitter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tweets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tweet_count" }
   ]
  },
  {
   "title": "Tweets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(tweet_count[5m])" }
   ]
  },
  {
   "title": "Following",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "twitter_following" }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "twitter_followers" }
   ]
  },
  {
   "title": "Listed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "listed_count" }
   ]
  },
  {
   "title": "Followers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(followers[5m])" }
   ]
  }
 ]
}